services:
  web:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/var/www
      - node_modules:/var/www/node_modules
    command: sh -c "npm install && sleep 10 && npm run dev"
    depends_on:
      database:
        condition: service_healthy
    networks:
      - job_prospection_api
    env_file:
    - .env

  database:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_DATABASE: job_prospection_api
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: user
      MYSQL_PASSWORD: userpassword
    volumes:
      - db_data:/var/lib/mysql
      - ./scripts:/docker-entrypoint-initdb.d
    networks:
      - job_prospection_api
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 3

volumes:
  db_data:
  node_modules:

networks:
  job_prospection_api:
    driver: bridge
