services:
  web:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/var/www
      - /var/www/node_modules
    depends_on:
      - database
    networks:
      - job_prospection_api

  database:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_DATABASE: job_prospection_api
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: user
      MYSQL_PASSWORD: userpassword
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./scripts:/docker-entrypoint-initdb.d
    networks:
      - job_prospection_api
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 3

  dbtest:
    image: mysql:latest
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: test_db
      MYSQL_USER: testuser
      MYSQL_PASSWORD: testpassword
    ports:
      - "3307:3306"
    volumes:
      - dbtest_data:/var/lib/mysql
    networks:
      - job_prospection_api
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 5s
      retries: 10

volumes:
  db_data:
  dbtest_data:

networks:
  job_prospection_api:
    driver: bridge
